apiVersion: v1
kind: Service
metadata:
  name: server-order-pod
  labels:
    name: server-order-pod
    app: ctse-app

spec:
  type: LoadBalancer
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    name: server-order-pod
    app: ctse-app